server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dessert_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: q18834366303

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.csu.userservice.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.csu.userservice: debug

oss:
  endpoint: ${ALIBABA_CLOUD_ENDPOINT}
  accessKeyId: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
  accessKeySecret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
  bucketName: ${ALIBABA_CLOUD_BUCKET_NAME}


