server:
  port: 8082

spring:
  application:
    name: product-service

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/product-service
    username: root
    password: amy20041113

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP

# MyBatis配置
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.csu.productservice.entity
  configuration:
    lazy-loading-enabled: false

# 日志配置
logging:
  level:
    com.example.userservice: debug